# This is the configuration used to check the rubocop source code.
require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  Enabled: false

# For RSpec tests
Metrics/BlockLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false
