language: ruby
rvm:
  - 2.6.5

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"

before_script:
  # - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER dummy WITH PASSWORD 'dummy';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS dummy_test;" -U postgres
  - psql -c "CREATE DATABASE dummy_test ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec/controllers spec/workers -R --format simple

cache:
  bundler: true
